theme: jekyll-theme-minimal
title: Alejandro Piad Morffis
description: Democratizing knowledge one keystroke at a time. Educator, researcher, coder, blogger. I write about AI, algorithms, education, philosphy, you know... mostly harmless stuff.
logo: /logo.jpg
